version: "3"
services:
  opa:
    image: openpolicyagent/opa:edge-static
    volumes:
      - "./policies:/policies"
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - /policies