version: "3"
services:
  proxy:
    image: traefik:v2.7
    command: --providers.docker -configFile=/conf/traefik.yaml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/conf/traefik.yaml
    env_file:
      - .env
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    expose:
      - 80
    labels:
      - traefik.http.routers.fe-http.rule=Host(`felixthe.dev`)
      - traefik.http.routers.fe-http.entrypoint=web
      - traefik.http.routers.fe-https.rule=Host(`felixthe.dev`)
      - traefik.http.routers.fe-https.entrypoint=websecure
