version: "3"
services:
  proxy:
    image: traefik:v2.7
    command: -configFile=/conf/traefik.yaml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/conf/traefik.yaml
    env_file:
      - .env
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    expose:
      - 80
    labels:
      - traefik.http.middlewares.https-redirectscheme.redirectscheme.scheme=https
      - traefik.http.routers.fe-http.rule=Host(`felixthe.dev`)
      - traefik.http.routers.fe-http.entryPoints=web
      - traefik.http.routers.fe-http.middlewares=https-redirectscheme@docker
      - traefik.http.routers.fe-https.rule=Host(`felixthe.dev`)
      - traefik.http.routers.fe-https.entryPoints=websecure
      - traefik.http.routers.fe-https.tls=true
      - traefik.http.routers.blog.tls.certresolver=cf


