version: "3"
services:
  proxy:
    image: traefik:v2.7
    command: --providers.docker -configFile=/conf/traefik.yaml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/conf/traefik.yaml
    env_file:
      - .env
