entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true

certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

api:
  dashboard: true
  insecure: true
log:
  level: DEBUG
